### ISSUE TITLE
unit test failing with recent Rust version

### ISSUE THREAD

**Issue by FrankReh** [triblesspace/tribles-rust#2]
I wonder if this unit test used to work but more recent rust versions were able to squeeze 8 bytes out of the struct or if the struct has changed but the unit test was no longer being run?

It was a little too hard given the cap file name for me to try to build with older commit versions. So I'll just put this out there and you can try on your system.

I needed to adjust the unit test like so.

```diff
diff --git a/src/pact.rs b/src/pact.rs
index 2c015d4..3902142 100644
--- a/src/pact.rs
+++ b/src/pact.rs
@@ -392,13 +392,13 @@ mod tests {
     #[test]
     fn branch_size() {
         assert_eq!(mem::size_of::<ByteTable4<Head<64, IdentityOrder>>>(), 64);
-        assert_eq!(mem::size_of::<BranchBody4<64, IdentityOrder>>(), 64 * 3);
-        assert_eq!(mem::size_of::<BranchBody8<64, IdentityOrder>>(), 64 * 4);
-        assert_eq!(mem::size_of::<BranchBody16<64, IdentityOrder>>(), 64 * 6);
-        assert_eq!(mem::size_of::<BranchBody32<64, IdentityOrder>>(), 64 * 10);
-        assert_eq!(mem::size_of::<BranchBody64<64, IdentityOrder>>(), 64 * 18);
-        assert_eq!(mem::size_of::<BranchBody128<64, IdentityOrder>>(), 64 * 34);
-        assert_eq!(mem::size_of::<BranchBody256<64, IdentityOrder>>(), 64 * 66);
+        assert_eq!(mem::size_of::<BranchBody4<64, IdentityOrder>>(), 64 * 3 - 8);
+        assert_eq!(mem::size_of::<BranchBody8<64, IdentityOrder>>(), 64 * 4 - 8);
+        assert_eq!(mem::size_of::<BranchBody16<64, IdentityOrder>>(), 64 * 6 - 8);
+        assert_eq!(mem::size_of::<BranchBody32<64, IdentityOrder>>(), 64 * 10 - 8);
+        assert_eq!(mem::size_of::<BranchBody64<64, IdentityOrder>>(), 64 * 18 - 8);
+        assert_eq!(mem::size_of::<BranchBody128<64, IdentityOrder>>(), 64 * 34 - 8);
+        assert_eq!(mem::size_of::<BranchBody256<64, IdentityOrder>>(), 64 * 66 - 8);
     }
 
     proptest! {

```

**Comment by somethingelseentirely** [comment]
Interesting 🤔, could you give me the rust version and arch of your system?

**Comment by FrankReh** [comment]
cargo 1.67.1 (8ecd4f20a 2023-01-10)

arch is x86_64

**Comment by somethingelseentirely** [comment]
Thanks! This looks like it's related to the architecture, as it works on my `stable-aarch64-apple-darwin` with `rustc 1.67.1 (d5a82bbd2 2023-02-07)`.
I'm gonna investigate this with MIRI!

**Comment by FrankReh** [comment]
Interesting. I suspect the sizes are a little important because of the union and wanting to be sure everything is where it is expected to be but maybe the test should just be disabled? Or whatever size the first one comes up with, the same kind of offset could be required of the rest.

**Comment by somethingelseentirely** [comment]
Well the test did what it was meant to do, detect weird size changes in the struct 😅.
It's mostly a sanity check that all the alignments work out, the BranchBody is essentially one (64byte) cache-line of node metadata, one cache-line of a key used for path compression in the trie, and then the hash table where each bucket corresponds to another cache-line.
If the head gets bigger or smaller (as seems to be the case here) then the assumption in the hash table, that iterating over a single bucket is cheap, no longer holds, because the buckets now get pushed across cache lines.

**Comment by FrankReh** [comment]
Nice. The test did what it was deigned to do. Glad I could help - totally by accident of course and without knowing what I was seeing. Congrats for digging into what many would have thought an anomaly.

**Comment by FrankReh** [comment]
Does this mean the 64 byte parts are not currently cache aligned?

**Comment by somethingelseentirely** [comment]
Yeah, that is what it looks like. The buckets themselves don't enforce any alignment, so my guess is that they're currently not well aligned.
They should probably aligned regardless of the context they are used in, and just force some padding bytes as a fallback.

**Comment by somethingelseentirely** [comment]
See #4
